python nerpa.py \
-a /share/home/azat/nerpa/asdb-jsons \
--smiles-tsv /share/home/azat/nerpa/nerpa2-antismashdb-kenan/compounds_kenan.tsv \
--col-id ID \
--col-smiles SMILES \
-o ./nerpa_results/antismashdb/ \
--force-output-dir \
--fast-matching \
--process-hybrids \
--min-num-matches-per-nrp 10 \
--max-num-matches-per-nrp 10 \
--max-num-matches 0 \
--threads 32