python nerpa.py \
-a ~/data/antismash_db5/jsons \
--smiles-tsv ./data/input/pnrpdb2.tsv \
--col-id ID \
-o ./nerpa_results/pnrpdb2_vs_antismash_db5 \
--force-output-dir \
--fast-matching \
--process-hybrids \
--min-num-matches-per-nrp 10 \
--max-num-matches-per-nrp 10 \
--max-num-matches 10000 \
--threads 32
