python nerpa.py \
-a /home/ilya/data/asdb5_beta2_fixed_records/jsons \
--smiles-tsv ./data/input/pnrpdb2.tsv \
--col-id ID \
-o ./nerpa_results/pnrpdb2_vs_antismash_db5_fixed_records_new \
--force-output-dir \
--fast-matching \
--process-hybrids \
--max-num-matches-per-bgc 10 \
--max-num-matches-per-nrp 10 \
--max-num-matches 10000 \
--threads 50
