rban_config: {default_monomers_file: rban_monomers_db.json, default_input_file: rban.input.json,
  default_output_file_name: rban.output.json, putative_hybrids_input_file: hybrid_monomers_input.json,
  putative_hybrids_output_file_name: hybrid_monomers_output.json}
rban_processing_config:
  SUPPORTED_RESIDUES: [Ala, Gly, Leu, Val, aThr/Thr, Ser, Ile/aIle, Cys, dhCys, Asn,
    Pro, Asp, Gln, Phe, Lys, dhAbu, Trp, dh-Ala, Glu, Arg, Abu, Tyr, Hpg, NMe-Val,
    His, diOH-Bz, NMe-Thr, NMe-Leu, Dab, NMe-Gly, Hiv, OH-Asp, NMe-Phe, bMe-Asp, bMe-Phe,
    Dhpg, OH-Asn, Orn, NMe-Cys, N2Me-Asn, Fo-OH-Orn, Met, bOH-Cl-Tyr, 3OH-Leu, bAla,
    bOH-Val, bLys, NMe-Hpr, 4Me-Pro, Dpr, OH-Orn, Hpr, aFo-Gly, bOH-Tyr, NMe-Ser,
    NFo-Ala, NFo-Val, 4Me-Hva, Hse, Ac-OH-Orn, NFo-Met, 4OH-Pro, NMe-aIle/NMe-Ile,
    NFo-Hpr, Hty, NMe-Ala, diMe-Cys, Cap, dh-Trp, NFo-Lys, 3Me-Glu, Cl-Tyr, NMe-Asn,
    3Me-Pro, NMe-OMe-Tyr, OMe-Thr, N2Me-bOH-Asn, 3OH-Pro, Aad, NMe-Hty, Pha, OH-His,
    aMe-Cys, Cl-Hpg, NAc-OH-Orn, NAc-Cys, Cl2-Pro, NMe-Tyr, NFo-Ile, NMe-Hpg, NMe-Bmt,
    2Dh-Mabu, 4Cl-Thr, bOH-Gln, NAc-Ala, NdMe-Ala, bbMe2-O-Met, Cl2-Hpg, bMe-Gln,
    bMe-Ile, NAc-Thr, NMe-NAc-Ile, NAc-Leu, NAc-3OH-Leu, Valol, Ac-Phe, NMe-OMe-Thr,
    NMe-Fo-OH-Orn, NFo-Ser, OH-dHpg, NMe-bMe-Leu/diMe-aIle, NFo-Cl-Tyr, NAc-Ile, Kyn,
    NMe-Pro, NAc-bMe-Phe, NFo-Leu, NFo-OH-Orn, CysA, OMe-Trp, NMe-Trp, NMe-OH-Orn,
    bOH-NMe-Val, ph-Gly/Ph-Gly, OH-dHpg, Ac-Trp, NMe-Ph-Gly, bMe-Br-Phe, NAc-Ac-OH-Orn,
    NAc-OH-Trp, Cl-NMe-Tyr, NFo-Arg, NMe-5OH-Cap, NMe-bOMe-Tyr, NMe-Cl-Trp, Br-Phe,
    NOMe-Ac-Val, NMe-bOH-Cl-Tyr, NFo-Cl-Hpg, NMe-Glu, NAc-aFo-Gly, bO-Met, b3Me-Glu,
    NAc-His, NFo-Cl2-Hpg, NFo-Hty, NMe-N2Me-bOH-Asn, NMe-bMe-Ile, NFo-OMe-Asp, NFo-diOH-Arg,
    3Me-Hty, NMe-3OH-Pro, NAc-bMe-Asp, NAc-OMe-Trp, NAc-Aad, NMe-Cap, NFo-Fo-OH-Orn,
    NFo-Tyr, NMe-3OH-Leu, NAc-Cl-Ile, 3Me-4Me-Gln, NMe-O2-Met, NAc-Bmt, 3OMe-Ala,
    NMe-4OH-Thr, NAc-bOH-Gln, NMe-Cl-Trp, NAc-Cl2-Pro, NMe-N2Me-Asn, NMe-bOH-Tyr,
    NAc-Cl-Hpg, NMe-bOMe-Asp, bbMe-NMe-Trp, NMe-3Me-4Me-Gln, b1Me-Trp, NAc-5Me-Pro,
    Ac-Ser, NAc-Br-Phe, NMe-Met, NAc-3Me-Phe, NFo-Dpr, NFo-Br-Trp, bMe-Asn, NMe-3Me-Pro,
    NAc-3Me-Hty, NAc-O2-Met, NFo-bOH-Tyr, NAc-Br-OH-Trp, NFo-Bmt, NMe-Asp, bOH-Asn,
    bbMe-Asn, NFo-Cl2-Pro, NFo-3Me-Glu, NMe-CysA, O-Met, NMe-4OH-Pro, NFo-bOH-Br-Phe,
    NAc-Tyr, NAc-bOH-Cl-Tyr, NAc-OH-His, NAc-3OH-5Me-Pro, NMe-Dpr, NFo-bMe-Gln, NFo-MeO-Glu,
    NAc-Ser, bCl-Trp, NAc-3Me-Pro, NMe-Gln, NFo-F-ph-Gly, NFo-His, NAc-Gln, NFo-Gln,
    b3Me-Hty, OMe-Asp, bOMe-Tyr, NMe-3Me-Hty, NAc-Glu, NAc-bOMe-Asp, NFo-O-Met, NFo-bOMe-Tyr,
    NMe-4Cl-Thr, NFo-O2-Met, NMe-dPhe, NtMe-Leu, NFo-Cl-Trp, NFo-Dab, NAc-1Me-Trp,
    MeO-Glu, NMe-bMe-Br-Phe, b5OH-Cap, NFo-bOMe-Asp, NMe-3Me-Glu, NAc-N2Me-Asn, NMe-aFo-Gly,
    b3Me-4Me-Gln, Cl3-NMe-dhLeu, bO2-Met, NFo-Thr, NMe-OH-Asp, NMe-Cl2-Pro, bOH-Br-Phe,
    NFo-3Me-Phe, gOH-NMe-Val, NFo-Asn, NFo-OMe-Thr, NFo-4Me-Pro, NAc-4OH-Thr, NAc-bOH-Val,
    NMe-Arg, NFo-Glu, bbNMe-NMe-Trp, NFo-bMe-Ile, bbOH-Br-Phe, bOH-Asp, NMe-bMe-Asn,
    bOH-NMe-Phe, NFo-Orn, NAc-Asp, NAc-OMe-Thr, Cl2-NMe-dhLeu, NMe-bMe-Asp, NFo-Phe,
    b3Me-Phe, bbOH-Cl-Tyr, NFo-1Me-Trp, bbOH-Gln, NMe-5Me-Pro, NAc-Dhpg, NAc-Arg,
    NMe-OMe-Ile, bOH-His, NMe-Cl-OH-Trp, bbOMe-Asp, F-ph-Gly, NAc-O-Met, NAc-Lys,
    baFo-Gly, bCl-Ile, NAc-4Me-Pro, NFo-OH-Asp, O2-Met, NAc-3Me-Glu, Br-Tyr, NFo-bbMe2-O-Met,
    NMe-OH-Ile, NAc-bMe-Gln, 5OH-Cap, NAc-OH-Asp, NFo-Aad, NMe-Aad, NMe-Kyn, NFo-3OH-5Me-Pro,
    NAc-bbMe2-O-Met, NMe-Br-OH-Trp, b4OH-Thr, NMe-bbMe2-O-Met, NAc-3Me-4Me-Gln, NFo-OH-His,
    NFo-Cl-Ile, NMe-diOH-Phe, NFo-4OH-Thr, NFo-diOH-Phe, NdMe-Leu, NAc-Br-Tyr, bOH-Orn,
    Cl3-2OH-NMe-Leu, bbMe-Asp, NMe-Lys, NAc-Cap, NMe-Br-Trp, NMe-Orn, NMe-Dhpg, NMe-Cl-Ile,
    NMe-OH-His, NAc-F-ph-Gly, 1Me-Trp, NFo-3Me-Hty, NAc-Br-Trp, NFo-Ac-Ser, NFo-bMe-Phe,
    NAc-Cl-Trp, NAc-bMe-Br-Phe, NAc-Dpr, NAc-bOMe-Tyr, NAc-Ac-Ser, NAc-N2Me-bOH-Asn,
    diOH-Arg, Br-OH-Trp, 3Me-Phe, NMe-Abu, NAc-4OH-Pro, 3OH-5Me-Pro, NMe-3OH-5Me-Pro,
    NFo-OMe-Trp, NAc-Hpr, b4Cl-Thr, NFo-bOH-Cl-Tyr, NFo-bOH-Val, NFo-Dhpg, bN2Me-Asn,
    NMe-Br-Phe, NFo-4Cl-Thr, bFo-OH-Orn, NFo-Kyn, OH-bLys, Cl3-NMe-Leu, NFo-CysA,
    NAc-bMe-Asn, NMe-bOH-Gln, NAc-Cl2-Hpg, NAc-Asn, NFo-bMe-Asn, NAc-OH-Asn, NFo-Br-Phe,
    NFo-bMe-Asp, NMe-Ac-OH-Orn, Ac-Val, NAc-bOH-Tyr, NFo-Br-Tyr, NFo-N2Me-bOH-Asn,
    NFo-OH-Asn, NMe-Br-Trp, NFo-Cys, NFo-4OH-Pro, diOH-Phe, bbMe-Br-Phe, bbMe-Phe,
    NFo-3OH-Pro, bbOMe-Tyr, NMe-OH-Asn, OH-Trp, NMe-1Me-Trp, bbMe-Gln, Br-NMe-Tyr,
    NMe-Cl-Hpg, bMeO-Glu, NMe-OH-Trp, NFo-Pro, b3OH-Leu, NFo-N2Me-Asn, NAc-Cl-Tyr,
    bBr-Trp, NAc-Fo-OH-Orn, NAc-Orn, NAc-Abu, NMe-F-ph-Gly, NMe-bOH-Br-Phe, NAc-Ph-Gly,
    Br-Trp, NMe-OMe-Trp, Cl3-5OH-NMe-Leu, NFo-Ac-OH-Orn, NFo-OH-Trp, NMe-Hse, NFo-aFo-Gly,
    NFo-3Me-4Me-Gln, NMe-bAla, Bmt, Ival, bBr-Tyr, Me2-Bmt, NAc-MeO-Glu, NFo-Abu,
    NMe-O-Met, bCl-Tyr, bAc-Ser, Ac-Pro, NFo-Hpg, bdiOH-Phe, NAc-Hse, NAc-Kyn, NMe-OMe-Asp,
    NFo-5OH-Cap, Cl2-NMe-Leu, bAc-OH-Orn, bbOH-Tyr, NAc-5OH-Cap, NMe-MeO-Glu, bOMe-Thr,
    bBr-OH-Trp, NFo-Trp, NAc-bOH-Br-Phe, NMe-3Me-Phe, NFo-Ph-Gly, 4OH-Thr, NAc-Dab,
    NFo-Br-OH-Trp, I-NMe-Tyr, bOH-Trp, NAc-OMe-Asp, bN2Me-bOH-Asn, NFo-3Me-Pro, NAc-Hpg,
    NAc-4Cl-Thr, Ac-Ival, NMe-Cl2-Hpg, NMe-bMe-Gln, bThr, NFo-Asp, NMe-bMe-Phe, NFo-Cap,
    NAc-diOH-Arg, NAc-Met, 5Me-Pro, NMe-His, NFo-bOH-Gln, NMe-4Me-Pro, NFo-3OH-Leu,
    NMe-Ac-Ser, NAc-3OH-Pro, NMe-Dab, NFo-5Me-Pro, NAc-diOH-Phe, bOMe-Asp, Cl-Ile,
    NFo-bMe-Br-Phe, NAc-Hty, NMe-diOH-Arg, bBr-Phe, Cl-Trp, NFo-Hse, bOMe-Trp, NAc-bMe-Ile,
    bdiOH-Arg, NAc-CysA, Aeo, NAc-Aeo, NFo-Aeo, NMe-Aeo, 3PAL, NAc-3PAL, NFo-3PAL,
    NMe-3PAL, 4PPro, NAc-4PPro, NFo-4PPro, NMe-4PPro, Alaol, Dht, NAc-Dht, NFo-Dht,
    NMe-Dht, GlyA, Hyv, NAc-Hyv, NFo-Hyv, NMe-Hyv, ICA, LDAP, NAc-tCl-Leu, NFo-tCl-Leu,
    NMe-tCl-Leu, tCl-Leu, Lyserg, Oiv, NAc-Piz, NFo-Piz, NMe-Piz, Piz, Sal]
  MIN_RECOGNIZED_NODES: 2
  CUT_LIPIDS: true
  PNP_BONDS: [AMINO, AMINO_TRANS, OXAZOLE_CYCLE, THIAZOLE_CYCLE, PYRIMIDINE_CYCLE,
    HETEROCYCLE]
antismash_parsing_config:
  MAX_DISTANCE_BETWEEN_GENES: 10000
  MAX_VARIANTS_PER_BGC: 100
  MAX_PERMUTATIONS_PER_BGC: 100
  SVM_SUBSTRATES: [Arg, Asp, Glu, Asn, Lys, Gln, Orn, Orn, Aad, Ala, Gly, Val, Leu,
    Ile, Abu, Iva, Ser, Thr, Hpg, dHpg, Cys, Pro, Pip, Phe, Tyr, Trp, Bza, Sal, Tyr]
  SVM_NOT_SUPPORTED_SCORE: -1.0
  SVM_NO_PREDICTION_SCORE: 0.0
  SCORING_TABLE_INDEX: substrate
  SCORING_TABLE_COLUMNS: [substrate, aa10_score, aa34_score, svm_single_amino_score,
    svm_small_cluster_score, svm_large_cluster_score, svm_physiochemical_class_score]
  ANTISMASH_DOMAINS_NAMES: {AMP-binding: A, PKS_AT: PKS, PKS_DH: PKS, PKS_DH2: PKS,
    PKS_DHt: PKS, PKS_Docking_CTERM: PKS, PKS_Docking_NTERM: PKS, PKS_ER: PKS, PKS_KR: PKS,
    PKS_KS: PKS, PKS_PP: PKS, PCP: PCP, Condensation: C, Cglyc: C, Heterocyclization: C,
    Condensation_Starter: C_STARTER, Condensation_LCL: C_LCL, Condensation_DCL: C_DCL,
    Condensation_Dual: C_DUAL, Epimerization: E, cMT: MT, nMT: MT, oMT: MT, Thioesterase: TE_TD,
    TD: TE_TD, NRPS-COM_Cterm: CTERM, NRPS-COM_Nterm: NTERM}
paths: {rban_dir: external_tools/rBAN, nerpa_monomers: configs/monomersdb_nerpa.json,
  nerpa_monomers_info: configs/monomer_names_table.tsv, aa_codes: configs/aa_codes.yaml,
  specificity_prediction_model: src/aa_specificity_prediction_model/specificity-model-26.joblib,
  configs_input: configs, configs_output: configs, scoring_config: configs/scoring_config.yaml,
  antismash_out_dir: antismash_output, report: report.tsv, matches_details: matches_details,
  default_results_root_dirname: nerpa_results, default_results_dirname_prefix: results_}
specificity_prediction_config:
  calibration: true
  apply_step_function: true
  calibration_step_function_steps: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001,
    0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.002, 0.002,
    0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002,
    0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002,
    0.002, 0.002, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003,
    0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.005, 0.005, 0.005, 0.005,
    0.005, 0.007, 0.007, 0.007, 0.007, 0.007, 0.007, 0.097, 0.097, 0.097, 0.097, 0.097,
    0.097, 0.097, 0.097, 0.097, 0.104, 0.104, 0.167, 0.167, 0.167, 0.167, 0.167, 0.167,
    0.167, 0.167, 0.167, 0.167, 0.167, 0.167, 0.877, 0.877, 0.877]
  normalize_scores: true
  apriori_residue_prob: {unknown: 0.4216385458340581, Trp: 0.0077404766046268916,
    Asp: 0.027048182292572623, Thr: 0.025917550878413638, Gly: 0.026265437467385633,
    Orn: 0.008697164724299879, Ala: 0.06131501130631414, Glu: 0.019220734040702733,
    Kyn: 0.00034788658897199514, Asn: 0.0141763785006088, Ile: 0.022873543224908678,
    Val: 0.04096364585145243, Aad: 0.00026091494172899633, Cys: 0.0008697164724299878,
    Pro: 0.06235867107323013, Gln: 0.03278831101061054, Leu: 0.07575230474865194,
    Lys: 0.006696816837710906, Phe: 0.019829535571403722, His: 0.003217950947990955,
    Ser: 0.02348234475560967, Abu: 0.01139328578883284, Bmt: 0.00026091494172899633,
    bAla: 0.0054792137763089235, Pen: 0.002000347886588972, Pip: 0.0026961210645329624,
    Hiv: 0.0066098451904679075, Arg: 0.009218994607757871, Tyr: 0.010610540963645852,
    Hty: 0.002435206122803966, Dab: 0.015220038267524787, Hse: 0.0018264045921029745,
    aThr: 0.0037397808314489477, Bza: 0.0013045747086449816, aIle: 0.0015654896503739782,
    Lac: 0.00287006435901896, oxoDec: 0.00017394329448599757, Dpr: 0.0026091494172899633,
    bLys: 0.00034788658897199514, Hpg: 0.010349626021916854, dHpg: 0.0037397808314489477,
    Iva: 0.0033918942424769525, Ant: 8.697164724299878e-05, Aol: 8.697164724299878e-05,
    Hda: 8.697164724299878e-05, Kiv: 8.697164724299878e-05, Piz: 8.697164724299878e-05,
    Ppa: 8.697164724299878e-05, Pyv: 8.697164724299878e-05, Sal: 8.697164724299878e-05}
  pseudo_counts: true
  pseudo_count_fraction: 0.1
  compute_evidence: true
