antismash_config: configs/antismash_config.yaml
antismash_processing_config: configs/antismash_processing_config.yaml
specificity_prediction_config: configs/specificity_prediction_config.yaml
rban_config: configs/rban_config.yaml
rban_processing_config: configs/rban_processing_config.yaml
hmm_scoring_config: configs/hmm_scoring_config.yaml
matching_config: configs/matching_config.yaml
cpp_matcher_exec: build/hmm_nrp_matcher
monomers_config: configs/monomers_config.yaml
output_config: configs/output_config.yaml
default_results_root_dirname: nerpa_results
