symlink_to_latest: nerpa_results/latest
configs_output: configs

antismash_out_dir: antismash_output

bgc_variants_dir: BGC_variants
nrp_variants_dir: NRP_variants
nrp_images_dir: NRP_images
rban_graphs: rban_graphs.yaml

matches_details: matches_details

report: report.tsv
html_report: report.html
logo: docs/img/logo.png
draw_molecules: True


rban_output_config:
    rban_output_dir: ''
    default_monomers_file: rban_monomers_db.json
    default_input_file: rban.input.json
    default_output_file_name: rban.output.json  # I know it's weird to have name instead of path, but that's rBAN quirks and I don't wanna mess with it
    putative_hybrids_input_file: hybrid_monomers_input.json
    putative_hybrids_output_file_name: hybrid_monomers_output.json

cpp_io_config:
    hmms_json: hmms.json
    nrp_linearizations_json: nrp_linearizations.json
    cpp_output_json: cpp_matching_output.json

bgc_variants_no_calibration_dir: BGC_variants_no_calibration  # for debugging purposes