alignment_step_frequency:  # calculated based on the number of times each alignment step is used in the "true" alignments
  MATCH: 0.9793486894360603
  NRP_MONOMER_SKIP: 0.010325655281969817
  BGC_MODULE_SKIP: 0.010325655281969817

bgc_module_skip_score:
  '': 0.01
  'START_OF_GENE': 0.02
  'END_OF_GENE': 0.02
  'START_OF_FRAGMENT,END_OF_FRAGMENT': 0.3
gene_skip_score:
  '': 0.03
bgc_fragment_skip_score:
  'START_OF_BGC': 0.1
  'END_OF_BGC': 0.1
  '': 0.01
nrp_monomer_insert_at_start_score:
  'START_OF_GENE,START_OF_FRAGMENT,START_OF_BGC': 0.2
  'START_OF_GENE,PKS_UPSTREAM_PREV_GENE': 0.3
  'START_OF_GENE,START_OF_FRAGMENT': 0.1
  '': 0.037
nrp_monomer_insert_score:
  '': 0.01
  'START_OF_GENE': 0.01
  'END_OF_GENE': 0.05
  'END_OF_GENE,END_OF_FRAGMENT': 0.1
  'END_OF_GENE,PKS_DOWNSTREAM_NEXT_GENE': 0.2
  'END_OF_GENE,END_OF_FRAGMENT,PKS_DOWNSTREAM_NEXT_GENE': 0.35
  'END_OF_GENE,END_OF_FRAGMENT,END_OF_BGC': 0.15
modification_score:
  { Mod_METHYLATION_BGC_True_NRP_True: 2.24344624136153, Mod_METHYLATION_BGC_True_NRP_False: -2.079726168996734,
    Mod_METHYLATION_BGC_False_NRP_True: -1.6842339933836148, Mod_METHYLATION_BGC_False_NRP_False: 0.08119172862635061,
    Mod_EPIMERIZATION_BGC_True_NRP_D: 1.5728181044740925, Mod_EPIMERIZATION_BGC_True_NRP_L: -1.7135261921932192,
    Mod_EPIMERIZATION_BGC_False_NRP_D: -0.1732481370950636, Mod_EPIMERIZATION_BGC_False_NRP_L: 0.03356504081882253,
    Mod_EPIMERIZATION_BGC_False_NRP_UNKNOWN: 0, Mod_EPIMERIZATION_BGC_True_NRP_UNKNOWN: 0}

chirality_score:
  BGC_False_NRP_L: 0.029
  BGC_False_NRP_D: -0.15
  BGC_False_NRP_UNKNOWN: 0  # weighted average of L and D scores
  BGC_True_NRP_L: -1.23
  BGC_True_NRP_D: 1.46
  BGC_True_NRP_UNKNOWN: -0.482  # weighted average of L and D scores

module_modification_frequency:
  METHYLATION: 0.17

module_epimerization_frequency: 0.243


max_gene_repetitions: 3
max_module_repetitions: 3

pks_residues: [CFA, Adda, Me-Suc, ADMAdda, C8:3(t2.t4.t6), DMAdda, C6:2(t2.t4)]



MAX_PERMUTATIONS: 6  # maximum number of permutations of NRP fragments allowed

heuristic_matching_cfg:
  LINEAR_DISCARD_PARAMS_AA_CONTENTS: [0.855099070490556, -0.388971585458635, 2.272684669081407]
  LINEAR_DISCARD_PARAMS_LENGTHS: [0.9854214280767362, -0.39833090934275733, 0.5878533443451871]
  LINEAR_DISCARD_PARAMS_CONS_PAIRS: [0.9624255237363057, -1.4645833697342432, 2.0845239151014265]
  NUM_TOP_PREDICTIONS: 1