ENABLE_DICTIONARY_LOOKUP: True  # use dictionary lookup for known aa34 codes
ENABLE_CALIBRATION: True  # should be set to True unless for debugging

nerpa_specificity_prediction_model: src/aa_specificity_prediction_model/specificity-model-unbalanced.joblib
paras_model: external_tools/paras/model.paras
a_domains_signatures: data/nerpa_internal/signatures.tsv
norine_monomers_info: data/nerpa_internal/norine_monomers_info.yaml  # used as apriori specificity probability

SVM_SUBSTRATES: [dHpg, Asn, Iva, Ile, Glu, Cys, Abu, Gly, Gln, Val, Ser, Arg, Asp,
    Hpg, Leu, Trp, Ala, Lys, Phe, Orn, Thr, Tyr, Aad, Bza, Pip, Pro]
SVM_NOT_SUPPORTED_SCORE: -1.0
SVM_NO_PREDICTION_SCORE: 0.0
SCORING_TABLE_INDEX: substrate
SCORING_TABLE_COLUMNS: [substrate, aa10_score, aa34_score, svm_single_amino_score,
    svm_small_cluster_score, svm_large_cluster_score, svm_physiochemical_class_score]

CALIBRATION_STEP_FUNCTION_STEPS_NERPA:
    [0.001, 0.002, 0.002, 0.002, 0.007, 0.007, 0.012,
    0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012,
    0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.012, 0.032,
    0.032, 0.032, 0.032, 0.032, 0.032, 0.032, 0.032, 0.039, 0.039, 0.039, 0.039, 0.039,
    0.039, 0.039, 0.039, 0.039, 0.039, 0.039, 0.039, 0.039, 0.136, 0.136, 0.136, 0.136,
    0.136, 0.136, 0.136, 0.136, 0.136, 0.136, 0.136, 0.273, 0.273, 0.273, 0.273, 0.273,
    0.273, 0.273, 0.273, 0.273, 0.333, 0.333, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6,
    0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.703, 0.703, 0.703, 0.703,
    0.703, 0.703, 0.703, 0.703, 0.703]

CALIBRATION_STEP_FUNCTION_STEPS_PARAS:
  [0.001, 0.013, 0.016, 0.039, 0.04,
   0.116, 0.116, 0.17, 0.24, 0.24,
   0.24, 0.32, 0.906, 0.938, 0.938,
   0.938, 0.94, 0.969, 0.969, 0.992]

PSEUDO_COUNT_FRACTION: 0.1
